### ISSUE TITLE
Update to hyper 0.12

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush-rs#132]
hyper 0.12 has a number of big changes so we've held off on upgrading.

Most of the work required is already done in the [chore/hyper0.12-take2 ](https://github.com/mozilla-services/autopush-rs/tree/chore/hyper0.12-take2) branch. What's left is:

- updating the branch to master
- finishing up the `Send` safe ClientRegistry, deciding on the best [lock solution for it ](https://github.com/mozilla-services/autopush-rs/commit/00685a63e67cea551f73c21389c77875280a3800)

The `Send`/locking requirement may affect our performance (on client registration and unregistration due to the locking, but possibly elsewhere). We should ship this change in its own release and load test it on stage.

**Comment by fzzzy** [comment]
I'm going to call this done, because updating to hyper 0.12 is done. However, we chose the best lock solution which is in tokio 0.2, which requires updating to hyper 0.13. So, this branch cannot be merged into master until the hyper 0.13 branch is done. This branch will live on, tracked under the upgrade to hyper 0.13 bug.

**Comment by tublitzed** [comment]
for reference, branch is here: https://github.com/mozilla-services/autopush-rs/tree/133-update-to-hyper-13
